name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

  workflow_dispatch:

permissions:
  actions: read
  contents: write
  pages: write

env:
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Start selenoid server
        uses: n-ton4/selenoid-github-action@master
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1

      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status

      - name: Get code
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Maven Test
        run: mvn clean test -Dselenide.browser=org.heyrmi.providers.SelenoidDriverProvider --no-transfer-progress

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: "./src/test/resources/config.properties"
          properties: "sendallureresults publishallureresults"

      - name: Result Sending
        if: steps.read_property.outputs.sendallureresults == 'yes'
        run: bash sendResultsSecurely.sh

      - name: Upload Allure Results
        if: ${{ (steps.read_property.outputs.sendallureresults == 'no') && (steps.read_property.outputs.publishallureresults == 'no') }}
        uses: actions/upload-artifact@v3
        with:
          name: Allure-Results
          path: ./allure-results

      - name: Get gh-pages
        uses: actions/checkout@v3
        if: steps.read_property.outputs.publishallureresults == 'yes'
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure History
        if: steps.read_property.outputs.publishallureresults == 'yes'
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: ./allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report
        if: steps.read_property.outputs.publishallureresults == 'yes'
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Send Slack Message
        if: ${{ github.event_name == 'push' }}
        # Contains Latest Allure Reports URL in the data block
        run: >
          curl -X POST -H 'Content-type: application/json' 
          --data '{"text":"Test completed and latest report pushed to GitHub Pages: heyrmi.github.io/Selenium-On-Steroids/${{ github.run_number }}"}' 
          ${{ secrets.SLACK_WEBHOOK_URL }}
